### ISSUE TITLE
Merge sorter uses 3n space

### ISSUE THREAD

**Issue by sebawild** [roarin-roran/Sorting#1]
The merge sorter stores the input plus 2 buffers, ping and pong; for production use, we should avoid that and only use one extra copy.

It's true that input is just a reference, but we create two copies.

**Comment by roarin-roran** [comment]
kk, will move the input storage outside the method (still really important to store it in development)

**Comment by roarin-roran** [comment]
handled - input will be stored by the manager, but that's not a component of the sorter, just its source of inputs etc
