### ISSUE TITLE
throw if not implemented for all interfaces

### ISSUE THREAD

**Issue by roarin-roran** [roarin-roran/Sorting#17]
all methods built on an interface should implement all methods of that interface - throw an error if not implemented

plan - informal version: ask the user if they want to proceed, so it's not too irritating if I'm using unit tests on a partially implemented class

**Comment by roarin-roran** [comment]
this has been implemented - I couldn't throw an error if __init__ was not implemented, because the init function must be called via super().__init__ to avoid complaints. 

proposed solution - don't throw if __init__ is not implemented

this caused several other complaints... but they can be safely ignored. they essentially come from the fact that we use informal interfaces with an expected return type, but the only thing the methods can do is throw an error, so they have no return type.

proposed solution - ignore these complaints from pycharm

would love a sign off here @sebawild, but I'm happy to close this

**Comment by sebawild** [comment]
There's a special type for functions that never return.

**Comment by sebawild** [comment]
And don't rely on pycharm for types, run mypy manually to be sure the code typechecks
