### ISSUE TITLE
experiment - running time vs k

### ISSUE THREAD

**Issue by roarin-roran** [roarin-roran/Sorting#28]
test for a few million elements, when sufficient infrastructure is in place

**Comment by sebawild** [comment]
Needs a bit more detail.
Is this running different non-adaptive methods for different k?

**Comment by roarin-roran** [comment]
I'd probably make a standard script and test each implemented method with several k values and a few million elements.

data is easy to generate, unless you're only interested in testing specific methods? the analysis will take a little time per method tested

**Comment by roarin-roran** [comment]
completed for all existing methods, may reopen when we want data for the paper, but the experiment is built.
