### ISSUE TITLE
local k value for the ends

### ISSUE THREAD

**Issue by roarin-roran** [roarin-roran/Sorting#29]
whenever k can be lower than the global value, it should be

edge effects can cause this, as well as other effects like concatenation before merging in the top-down mergesort

look into the best time to cap this - above or in the merger layer, probably.

**Comment by roarin-roran** [comment]
@sebawild should this be small fry? idk if it's optional

**Comment by sebawild** [comment]
I'd leave this to the merger to figure out.  It is likely the same reasoning no matter what the sorter layer wants.
I would say priority is low atm.

**Comment by roarin-roran** [comment]
kk, will small fry it (I should probably have called that tag "optional", but I quite like small fry) for now

**Comment by roarin-roran** [comment]
reviewing the code - this is the way that I've done it! it actually seems easier and more natural to not force blocks to be blocks of k, for example. you have to reserve some generality, and this may be needed later on if we try different ipqs for some reason, but my code to date allows any k value at any level and allows ends to just be the last up to k characters
