### ISSUE TITLE
defaults potentially allow for a horrible bug

### ISSUE THREAD

**Issue by roarin-roran** [roarin-roran/Sorting#34]
if default values are used for merger_init and merger_ipq_init (and potentially other similar methods), then an implementation error could lead to the default value being used instead of the desired value - a tricky bug to even notice, as the code will all work, but changing internal options (which may have no significant effect or may have a huge effect) would have no effect.

solution: test for this! add a broken merger and broken mergerIPQ, and a unit test that ensures that switching to them breaks the code (aka that non-default values reach all the way to the bottom and are actually used).

at the same time, update default value policy: interface determines global default values("best method"), which are overridden only if needed, either by a user class (this sorter gets on better with this merger than the global default), or by the end user(who might want to sort using a particular combination of sorter, merger, and IPQ for whatever reason)

**Comment by sebawild** [comment]
Not sure if you can make this test water tight.
It could fail side it is used in one part while not being passed on...

**Comment by roarin-roran** [comment]
hmmm. so what you're saying is that if I drop a bad merger in it could go down far enough to cause a failure and pass the test, without hitting the bottom, so there could still be a problem?

**Comment by roarin-roran** [comment]
because the test tests that the inputted method is used, not that it's the only method that's used...

**Comment by roarin-roran** [comment]
right, try this:

create an object that everything in the class extends called "policy", which contains three lists. 

whenever you make a merge IPQ, merger, or sorter, record to the relevant list what you used if it doesn't appear on the list

check in testing that only one merger/merge IPQ appears.



advantage: apparently watertight
disadvantage: yet another class, another thing that has to be referenced in the init (and failing to do that will break the seal and stop this from working)

**Comment by roarin-roran** [comment]
I can implement either test, or both, but even without them I prefer this way. both our approaches allow for an error where the wrong modular option is selected, both errors are equally hard to find (the experiments will be long and repetitive, and the correct answers will be obscure - the code is spread out, and will be harder to manually check), but this way seems to have manifest advantages.

**Comment by roarin-roran** [comment]
I've made a policy of writing out all __init__ calls in full, and using False as a default value when the user wants the policy to be determined lower down - as long as I stick to this very simple policy, the error you're worried about will be caught by the simple test, and is very hard to cause
