### ISSUE TITLE
Indices inclusive exclusive

### ISSUE THREAD

**Issue by sebawild** [roarin-roran/Sorting#5]
Wherever we pass around list slices via indices, eg here
https://github.com/roarin-roran/Sorting/blob/main/mergeSorter.py#L37-L38
there should be a comment whether they are inclusive or not.

I strongly suggest we adopt the Java/C++ convention that start points are always inclusive and end points are always exclusive.

**Comment by roarin-roran** [comment]
comment added - this is the convention I'm using.
