### ISSUE TITLE
Types in MergerIPQ

### ISSUE THREAD

**Issue by sebawild** [roarin-roran/Sorting#7]
The type annotations in MergerIPQ are suspicious

 ​# noinspection PyTypeChecker 
 ​PRIORITY_TYPE​: ​Type​[​Type​] ​=​ ​int

The no inspection means this is not really used?

Later, the list annotation should be List[PRIORITY_TYPE].

Instead of fixing the type for PRIORITY_TYPE, we want this to be generic (so you can create pqs with different object types). Don't know the syntax for that yet.

**Comment by roarin-roran** [comment]
the #noinspection thing is a PyCharm artifact - I can't actually see it in there at all.

I can implement the PRIORITY_TYPE thing (though it'll be type [PRIORITY_TYPE, int], because the index will always be an integer)

**Comment by roarin-roran** [comment]
#noinspection is a pycharm artefact - it prevents the reporting of an error resulting from the way we do this (not one that actually does anything bad)

fixed the type for peek, though it's [int, PRIORITY_TYPE], because list indecies are always int

**Comment by sebawild** [comment]
> #noinspection is a pycharm artefact - it prevents the reporting of an error resulting from the way we do this (not one that actually does anything bad)

Not an artifact, it tells PyCharm to *ignore* this annotation, so unless you run `mypy` manually, you won't see any typing errors, rending the annotation pointless.

> fixed the type for peek, though it's [int, PRIORITY_TYPE], because list indecies are always int
Not sure I agree. The *list* contains the priorities only; the index is implicit.

(How can I reopen issues?)

**Comment by sebawild** [comment]
Update: Here's the solution: `PRIORITY_TYPE` should be a `TypeVar`:
https://docs.python.org/3.8/library/typing.html#generics

**Comment by sebawild** [comment]
`[int, PRIORITY_TYPE]` is not a valid type annotation afaik. Should be `Tuple[int, PRIORITY_TYPE]`

**Comment by roarin-roran** [comment]
I see. I was thinking of using a tuple - will make the cahnges

**Comment by roarin-roran** [comment]
there's a better way than using a list or a tuple actually - python can return multiple comma separated values, and the result is much clearer

**Comment by sebawild** [comment]
Check the return type, i think that IS a tuple, just without parens

**Comment by roarin-roran** [comment]
huh, cool

**Comment by roarin-roran** [comment]
should be sorted - Pycharm doesn't like the explicit naming of tuples, so I just wrapped the variables in brackets
